title: Выпускная дипломная работа
author: Vladislav Zlobin
email: mailme@gmail.com
description: # this means to ignore newlines until "baseurl:"
  Сайт посвящён ключевым моментам и принципам функционирования роевого интеллекта в мультиагентной среде на примере метода роя частиц и метода оптимизации подражанием муравьиной колонии. 
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
